### ISSUE TITLE
data_1000

### ISSUE THREAD

**Issue by Jbangliang** [kdmsit/crysxpp#2]
![image](https://github.com/kdmsit/crysxpp/assets/136157142/3256e2f3-8668-423a-837e-f0d821d7e711)
Hello, this is an excellent project. I have been troubled by a question，in predict and pretrain scripts。They consist the data_1000 data, I couldn't find what you provided in the document.

**Comment by kdmsit** [comment]
Hello, sorry for the confusion. That is just the default data path we used for training. You can use '../data/' for using the existing data available in the repo. Also, you can use your own data path here.

**Comment by kdmsit** [comment]
closing..
